vision in sim
1757WestwoodRobotics/2024-Crescendo pull request #46
Opened 2024-02-18 00:10 UTC by lmaxwell24

implements #31

2024-02-18 15:53 UTC, icai0 commented on subsystems/visionsubsystem.py
> +        self.targToCamAngle = Rotation2d(
what angle is this

2024-02-18 16:13 UTC, icai0 requested changes

2024-02-18 16:13 UTC, icai0 commented on subsystems/visionsubsystem.py
> +        self.number = number
not used anywhere

2024-02-18 16:13 UTC, icai0 commented on subsystems/visionsubsystem.py
> +    # this is really bad
:(

2024-02-18 16:17 UTC, icai0 commented on subsystems/visionsubsystem.py
> +                botPose, camera.key, simPose3d, rel.camToTarg
first argument should be the camera's pose

2024-02-18 16:21 UTC, icai0 commented on subsystems/visionsubsystem.py
> +                botPose, camera.key, simPose3d, rel.camToTarg
![image](https://github.com/1757WestwoodRobotics/2024-Crescendo/assets/23267389/91e882c6-be92-471b-8345-4ea00abe0357)
axis on the ground comes from botPose

2024-02-19 01:51 UTC, icai0 approved these changes

2024-02-19 03:40 UTC, LandonBayer approved these changes

2024-02-19 03:41 UTC, merged