Go to waypoint
1757WestwoodRobotics/2024-Crescendo pull request #47
Opened 2024-02-18 02:40 UTC by icai0

goes to the closest waypoint (speaker, amp, source)

2024-02-18 02:47 UTC, lmaxwell24 requested changes

2024-02-18 02:47 UTC, lmaxwell24 commented on ControlScheme.json
> +    "temporary"
nuh uh use the actual control we already added for that exact feature

2024-02-18 02:47 UTC, lmaxwell24 commented on operatorinterface.py
> +        self.goToAmp = getButtonBindingOfName("goToAmp")
no :(

2024-02-18 02:51 UTC, lmaxwell24 approved these changes, later dismissed

2024-02-18 02:51 UTC, lmaxwell24 commented on constants.py
> +    kMaxWheelLinearVelocity / 2,
eventually we can go faster but not rn is fine

2024-02-18 02:51 UTC, lmaxwell24 commented
legit github backends are being silly and thats kinda it
if theres a second approve I will force merge

2024-02-19 03:41 UTC, LandonBayer submitted a review, later dismissed

2024-02-19 03:44 UTC, merged